#!/bin/bash -e
# SUBLIMED1D compile script
# This file is part of SUBLIMED1D (SUBlimating gases in LIME, version D1D)
#
# Copyright (C) 2006-2014 Christian Brinch
# Copyright (C) 2015-2017 The LIME development team
# Copyright (C) 2023 Martin Cordiner and Kristen Darnell (NASA GSFC)

export PATHTOLIME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
vernum=`grep VERSION ${PATHTOLIME}/src/lime.h` | awk '{print $3}' | sed s/\"//g

# Set up the PATHTOLIME, LD_LIBRARY_PATH and WORKDIR variables
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PATHTOLIME}/lib
export WORKDIR=$PWD

# Compile the code
pushd ${PATHTOLIME} >> /dev/null
make -s EXTRACPPFLAGS="-DNO_NCURSES -DFASTEXP" MODELS=$WORKDIR/src/model.c TARGET=$WORKDIR/sublimed1dc DOTEST=$do_test VERBOSE=$verbose
# USEHDF5="yes"
make -s limeclean

exit 0
